'use server';

import prisma from '@/lib/db';
import { auth } from '@/lib/auth';
import { headers } from 'next/headers';

export type ExportFormat = 'json' | 'markdown';

interface ExportReview {
  id: string;
  prNumber: number;
  prTitle: string;
  prUrl: string;
  review: string;
  status: string;
  createdAt: Date;
  repository: {
    fullName: string;
    owner: string;
    name: string;
  };
}

export async function getReviewForExport(reviewId: string): Promise<ExportReview | null> {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  if (!session) {
    throw new Error('Unauthorized');
  }

  const review = await prisma.review.findFirst({
    where: {
      id: reviewId,
      repository: {
        userid: session.user.id,
      },
    },
    include: {
      repository: {
        select: {
          fullName: true,
          owner: true,
          name: true,
        },
      },
    },
  });

  return review;
}

function formatReviewAsMarkdown(review: ExportReview): string {
  const lines: string[] = [];

  lines.push(`# AI Code Review: ${review.prTitle}`);
  lines.push('');
  lines.push(`**Repository:** ${review.repository.fullName}`);
  lines.push(`**PR Number:** #${review.prNumber}`);
  lines.push(`**PR URL:** ${review.prUrl}`);
  lines.push(`**Status:** ${review.status}`);
  lines.push(`**Reviewed:** ${review.createdAt.toISOString()}`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(review.review);
  lines.push('');
  lines.push('---');
  lines.push('*Generated by AI PR Reviewer — https://github.com/AnitSarkar123/AI_PR_REVIEWER*');

  return lines.join('\n');
}

function formatReviewAsJson(review: ExportReview): string {
  return JSON.stringify(
    {
      metadata: {
        id: review.id,
        prNumber: review.prNumber,
        prTitle: review.prTitle,
        prUrl: review.prUrl,
        status: review.status,
        repository: review.repository.fullName,
        reviewedAt: review.createdAt.toISOString(),
      },
      content: review.review,
      generator: {
        name: 'AI PR Reviewer',
        url: 'https://github.com/AnitSarkar123/AI_PR_REVIEWER',
      },
    },
    null,
    2,
  );
}

export async function exportReview(
  reviewId: string,
  format: ExportFormat,
): Promise<{ content: string; filename: string } | null> {
  const review = await getReviewForExport(reviewId);
  if (!review) return null;

  const safeName = review.repository.fullName.replace('/', '-');
  const timestamp = review.createdAt.toISOString().split('T')[0];

  if (format === 'markdown') {
    return {
      content: formatReviewAsMarkdown(review),
      filename: `ai-review-${safeName}-pr-${review.prNumber}-${timestamp}.md`,
    };
  }

  return {
    content: formatReviewAsJson(review),
    filename: `ai-review-${safeName}-pr-${review.prNumber}-${timestamp}.json`,
  };
}
